import { Header } from "../../components/Header";
import { IconArrowUpRight } from "../../components/icons";
import { PROJECTS } from "../../data";
const copy = [
  { title: "Polvor Technology and Software", summary: "A software company built to deliver ambitious digital products with clarity, reliability, and long-term vision.", points: ["Technical leadership across architecture, infrastructure, and delivery.", "Business needs translated into viable, maintainable products.", "A development operation built from independent projects into a company."] },
  { title: "Agency Manager", summary: "An original management platform designed around the real routine of agencies, from clients and projects to delivery and finance.", points: ["Product conceived from a real operational problem.", "Roadmap, experience, and development led end to end.", "Infrastructure and releases designed for continuous evolution."] },
  { title: "WordPress & custom projects", summary: "The foundation of the journey: websites, themes, plugins, and production systems delivered and maintained since the age of 14.", points: ["Custom development and ongoing production support.", "Performance, technical SEO, and security improvements.", "Migrations, servers, and backups for an active client base."] },
];
export const metadata = { title: "Work · Lucas Ritter Dias" };
export default function WorkPage() { return <><Header/><main className="route-page"><header className="route-hero"><p>Selected projects</p><h1>Work built<br/><em>to last.</em></h1><span>Digital products, platforms, and systems designed for the real world.</span></header><section className="route-projects">{PROJECTS.map((p,i) => <article className="route-project" key={p.slug}><div className="route-project-number">0{i+1}</div><div><p>{p.statusLabel} · {p.domain}</p><h2>{copy[i].title}</h2><strong>{copy[i].summary}</strong><ul>{copy[i].points.map(point => <li key={point}>{point}</li>)}</ul><div className="chips">{p.chips.map(c => <span className="chip" key={c.label}><i style={{"--dot":c.dot} as React.CSSProperties}/>{c.label}</span>)}</div><a className="route-link" href={p.href} target="_blank" rel="noreferrer">Visit project <IconArrowUpRight/></a></div></article>)}</section></main></>; }
